import type { ReactNode } from 'react'
import type { ProjectedOrganizationProfile } from '../../projection/types'
import { Card, Fact, StatePresentation } from '../components/WorkbenchPrimitives'

const DISPLAY_LIMIT = 6

export interface OrganizationInspectorProps {
  organization: ProjectedOrganizationProfile
  onInspectPerson: (personId: string) => void
  onInspectOrganization: (organizationId: string) => void
  onShowMap: (cellId: string) => void
  onShowHistory: () => void
}

/** Displays only the bounded organization evidence carried by the projection. */
export function OrganizationInspector({ organization, onInspectPerson, onInspectOrganization, onShowMap, onShowHistory }: OrganizationInspectorProps) {
  const roleCounts = Object.entries(organization.roleCounts).sort(([a], [b]) => a.localeCompare(b))
  const goods = Object.entries(organization.ownedGoods ?? {}).sort(([a], [b]) => a.localeCompare(b))
  const membership = organization.latestMembershipEvidence
  return <section className="organization-inspector" aria-label={`${organization.name} organization evidence`}>
    <div className="organization-inspector__identity"><span className="eyebrow">ORGANIZATION EVIDENCE</span><strong>{organization.name}</strong><small>{organization.definitionName} · {organization.id}</small></div>
    <div className="organization-inspector__actions" aria-label="Organization navigation"><button type="button" onClick={() => onShowMap(organization.locationCellId)}>Show location</button><button type="button" onClick={onShowHistory}>Show history</button></div>
    <InspectorSection title="Historical identity" subtitle="Recorded institutional status and lineage; related organizations remain separate inspectors">
      <div className="organization-inspector__facts"><Fact label="Status" value={organization.status ?? 'Unavailable'} /><Fact label="Specialization" value={organization.specialization ?? 'Unavailable'} /><Fact label="Origin" value={organization.lineage?.origin ?? 'Unavailable'} /><Fact label="Formed" value={organization.lineage ? `Tick ${organization.lineage.formedTick}` : 'Unavailable'} /></div>
      {organization.closedMembership && <EvidenceDetails label={`Membership at closure · tick ${organization.closedMembership.tick}`} evidence={organization.closedMembership} onPerson={onInspectPerson} personIds={organization.closedMembership.members.slice(0, DISPLAY_LIMIT).map((member) => member.personId)} />}
      <OrganizationLinks label="Parent organizations" organizationIds={organization.lineage?.parentOrganizationIds ?? []} empty="No parent organizations are recorded." onInspectOrganization={onInspectOrganization} />
      <BoundedEvidence label="Structural transition evidence" records={organization.latestTransitionEvidence ?? []} render={(trace) => <EvidenceDetails label={`Transition ${trace.sequence} · ${trace.kind} · tick ${trace.tick}`} evidence={trace} onOrganization={onInspectOrganization} organizationIds={[...trace.sourceOrganizationIds, ...trace.resultOrganizationIds]} />} />
      {organization.structuralLimitReason && <StatePresentation state="unavailable" title="Structural size limit">{organization.structuralLimitReason === 'member-limit' ? 'This organization exceeds the 128-member structural limit.' : 'This account exceeds the 128-good structural limit.'} Splits, mergers, and dissolution are not evaluated while it exceeds this limit.</StatePresentation>}
    </InspectorSection>
    <InspectorSection title="Purpose and membership" subtitle="Recorded definition and explicit membership roles">
      <div className="organization-inspector__facts"><Fact label="Kind" value={organization.kind} /><Fact label="Members" value={String(organization.memberCount)} /><Fact label="Service capacity" value={String(organization.serviceCapacity)} /><Fact label="Lifecycle" value={organization.lifecycleStatus} /></div>
      <LabelledList label="Purposes" values={organization.purposeIds} empty="No purposes are recorded by this definition." /><LabelledList label="Allowed roles" values={organization.allowedMemberRoleIds} empty="No member roles are recorded by this definition." />
      <div className="organization-inspector__labelled-list"><span>Observed role counts</span>{roleCounts.length === 0 ? <small>No explicit members are projected.</small> : <ul>{roleCounts.map(([role, count]) => <li key={role}><code>{role}</code><b>{count}</b></li>)}</ul>}</div><LabelledList label="Shared rules" values={organization.sharedRuleIds} empty="No shared rules are recorded." />
      {membership ? <EvidenceDetails label="Latest membership evidence" evidence={membership} onPerson={onInspectPerson} personIds={[membership.personId]} /> : <StatePresentation state="empty" title="No membership evidence">No retained membership transition is projected for this organization.</StatePresentation>}
    </InspectorSection>
    <InspectorSection title="Owned account" subtitle="Institution holdings only; member holdings are separate">
      {organization.ownedResourcesStatus === 'not-modeled' ? <StatePresentation state="unavailable" title="No owned account modeled">This organization has no projected institution-owned asset account.</StatePresentation> : organization.ownedCurrencyUnits === undefined || organization.ownedGoods === undefined ? <StatePresentation state="unavailable" title="Owned account balance unavailable">An owned account is indicated, but its current balance was not included in this projection.</StatePresentation> : <><div className="organization-inspector__facts"><Fact label="Currency units" value={String(organization.ownedCurrencyUnits)} /></div><LabelledList label="Goods" values={goods.map(([id, amount]) => `${id}: ${amount}`)} empty="The owned account is present and currently records zero goods." /><BoundedEvidence label="Asset transfer evidence" records={organization.latestAssetTransferEvidence ?? []} render={(trace) => <EvidenceDetails label={`Transfer ${trace.sequence} · tick ${trace.tick}`} evidence={trace} onOrganization={onInspectOrganization} organizationIds={[trace.from, trace.to].filter((party) => party.kind === 'organization').map((party) => party.id)} />} /></>}
    </InspectorSection>
    <InspectorSection title="Observer reputation" subtitle="Separate observer records; no global reputation score">
      {organization.reputationStatus === 'not-measured' ? <StatePresentation state="unavailable" title="Reputation not measured">No observer reputation ledger is modeled for this organization.</StatePresentation> : <><ObserverList observers={organization.reputationByObserver ?? []} onInspectPerson={onInspectPerson} onInspectOrganization={onInspectOrganization} /><BoundedEvidence label="Recent observations" records={organization.latestReputationEvidence ?? []} render={(observation) => <EvidenceDetails label={`Observation ${observation.sequence} · tick ${observation.tick}`} evidence={observation} onPerson={onInspectPerson} onOrganization={onInspectOrganization} personIds={observation.observer.kind === 'person' ? [observation.observer.id] : []} organizationIds={observation.observer.kind === 'organization' ? [observation.observer.id] : []} />} /></>}
    </InspectorSection>
    <InspectorSection title="Leadership and succession" subtitle="Engine-owned office evidence, separate from member roles">
      {organization.leadershipStatus === 'not-modeled' ? <StatePresentation state="unavailable" title="Leadership not modeled">No leadership office is recorded for this organization.</StatePresentation> : <><div className="organization-inspector__facts"><Fact label="Office role" value={organization.leaderRoleId ?? 'Unavailable'} /><Fact label="Status" value={organization.leadershipStatus} /><Fact label="Term started" value={organization.leadershipTermStartedTick === undefined ? 'Unavailable' : `Tick ${organization.leadershipTermStartedTick}`} /></div>{organization.leaderPersonId && <button type="button" className="organization-inspector__leader" onClick={() => onInspectPerson(organization.leaderPersonId!)}>Inspect leader: {organization.leaderPersonId}</button>}<BoundedEvidence label="Leadership and succession evidence" records={organization.latestLeadershipEvidence ?? []} render={(trace) => <EvidenceDetails label={`Leadership ${trace.sequence} · ${trace.outcome} · tick ${trace.tick}`} evidence={trace} onPerson={onInspectPerson} personIds={[trace.previousLeaderPersonId, trace.selectedLeaderPersonId, ...trace.candidates.map((candidate) => candidate.personId)].filter((id): id is string => Boolean(id))} />} /></>}
    </InspectorSection>
    <InspectorSection title="Decisions" subtitle="Pending proposals and resolved, structured decision evidence">
      {organization.decisionStatus === 'not-modeled' ? <StatePresentation state="unavailable" title="Decisions not modeled">No decision policy state is recorded for this organization.</StatePresentation> : <><BoundedEvidence label="Pending proposals" records={organization.pendingDecisions ?? []} render={(proposal) => <EvidenceDetails label={`Proposal ${proposal.sequence} · policy ${proposal.policyId}`} evidence={proposal} onPerson={onInspectPerson} personIds={proposal.participantIds} />} /><BoundedEvidence label="Resolved decisions" records={organization.latestDecisionResolutions ?? []} render={(resolution) => <EvidenceDetails label={`Resolution ${resolution.sequence} · ${resolution.selectedAlternativeId} · tick ${resolution.resolvedTick}`} evidence={resolution} onPerson={onInspectPerson} personIds={resolution.participantIds} />} /></>}
    </InspectorSection>
    <p className="organization-inspector__boundary">Recent evidence is limited to retained records. Open recorded history to investigate earlier events.</p>
  </section>
}

function InspectorSection({ title, subtitle, children }: { title: string; subtitle: string; children: ReactNode }) { return <Card className="organization-inspector__section"><h3>{title}</h3><p>{subtitle}</p>{children}</Card> }
function LabelledList({ label, values, empty }: { label: string; values: readonly string[]; empty: string }) { return <div className="organization-inspector__labelled-list"><span>{label}</span>{values.length ? <ul>{values.map((value) => <li key={value}><code>{value}</code></li>)}</ul> : <small>{empty}</small>}</div> }
function OrganizationLinks({ label, organizationIds, empty, onInspectOrganization }: { label: string; organizationIds: readonly string[]; empty: string; onInspectOrganization: (id: string) => void }) { return <div className="organization-inspector__labelled-list"><span>{label}</span>{organizationIds.length ? <ul>{organizationIds.map((id) => <li key={id}><button type="button" onClick={() => onInspectOrganization(id)}>Organization: {id}</button></li>)}</ul> : <small>{empty}</small>}</div> }
function ObserverList({ observers, onInspectPerson, onInspectOrganization }: { observers: NonNullable<ProjectedOrganizationProfile['reputationByObserver']>; onInspectPerson: (id: string) => void; onInspectOrganization: (id: string) => void }) { const shown = observers.slice(0, DISPLAY_LIMIT); return <div className="organization-inspector__labelled-list"><span>Current by observer (showing {shown.length} of {observers.length} projected)</span>{shown.length ? <ul>{shown.map((entry) => <li key={`${entry.observer.kind}:${entry.observer.id}`}><button type="button" onClick={() => entry.observer.kind === 'person' ? onInspectPerson(entry.observer.id) : onInspectOrganization(entry.observer.id)}>{entry.observer.kind}: {entry.observer.id}</button><b>{entry.valuePermille}‰</b><small>observation {entry.lastObservationSequence} · tick {entry.lastObservedTick}</small></li>)}</ul> : <small>No observers currently have retained reputation evidence.</small>}</div> }
function BoundedEvidence<T>({ label, records, render }: { label: string; records: readonly T[]; render: (record: T) => ReactNode }) { if (records.length === 0) return <StatePresentation state="empty" title={`No ${label.toLowerCase()}`}>No retained records are projected.</StatePresentation>; const shown = records.slice(-DISPLAY_LIMIT).reverse(); return <div className="organization-inspector__evidence"><span>{label} (showing {shown.length} of {records.length} projected)</span>{shown.map((record, index) => <div key={index}>{render(record)}</div>)}</div> }
function EvidenceDetails({ label, evidence, onPerson, onOrganization, personIds = [], organizationIds = [] }: { label: string; evidence: unknown; onPerson?: (id: string) => void; onOrganization?: (id: string) => void; personIds?: readonly string[]; organizationIds?: readonly string[] }) { return <details className="organization-inspector__details"><summary>{label}</summary><div className="organization-inspector__evidence-links">{[...new Set(personIds)].map((id) => <button type="button" key={`person:${id}`} onClick={() => onPerson?.(id)}>Person: {id}</button>)}{[...new Set(organizationIds)].map((id) => <button type="button" key={`organization:${id}`} onClick={() => onOrganization?.(id)}>Organization: {id}</button>)}</div><pre>{JSON.stringify(evidence, null, 2)}</pre></details> }
