import { expect, test } from '@playwright/test'

test('creates, steps, inspects, and saves a deterministic world', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByText('Seeded Valley')).toBeVisible()
  await page.getByRole('button', { name: 'food', exact: true }).click()
  await expect(page.getByRole('button', { name: 'food', exact: true })).toHaveClass(/active/)
  await expect(page.getByText('Day 0 · 00:00')).toBeVisible()
  await page.getByTitle('Advance one hour').click()
  await expect(page.getByText('Day 0 · 01:00')).toBeVisible()
  await page.getByPlaceholder('Snapshot name').fill('First hour')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByText('First hour')).toBeVisible()
  await expect(page.getByText('CLOCK ADVANCED')).toBeVisible()
  await page.getByRole('button', { name: /Inspect person-/ }).first().click()
  await expect(page.getByText('Person inspector')).toBeVisible()
  await expect(page.getByText('Person hooked')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Current condition', exact: true })).toBeVisible()
  await expect(page.locator('#need-variables-heading')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Core dispositions', exact: true })).toBeVisible()
  await expect(page.locator('[data-variable-id="person.trait.curiosity"]')).toBeVisible()
  await expect(page.locator('[data-variable-id="person.trait.riskTolerance"]')).toBeVisible()
  await expect(page.locator('[data-variable-id="person.trait.sociability"]')).toBeVisible()
  await expect(page.locator('[data-variable-id="person.trait.trustPropensity"]')).toBeVisible()
  await expect(page.locator('[data-variable-id="person.trait.conformity"]')).toBeVisible()
  await expect(page.locator('[data-variable-id="person.trait.persistence"]')).toBeVisible()
  await expect(page.getByText('Why this action?')).toBeVisible()
  await expect(page.getByText('Baseline')).toBeVisible()
  const currentStateContributions = page.locator('#contribution-current-state').locator('..')
  await expect(currentStateContributions).toBeVisible()
  await expect(currentStateContributions.locator('[data-source-id]').first()).toBeVisible()
  await expect(currentStateContributions).toContainText(/Hunger|Fatigue/)
  await expect(page.getByText(/selection probability/)).toBeVisible()
  const canvasHeight = await page.getByLabel('Hex world map').evaluate((canvas) => canvas.clientHeight)
  expect(canvasHeight).toBeGreaterThan(250)
  expect(canvasHeight).toBeLessThanOrEqual(800)
  const inspectorDimensions = await page.locator('.right-panel').evaluate((panel) => ({ clientHeight: panel.clientHeight, scrollHeight: panel.scrollHeight, overflowY: getComputedStyle(panel).overflowY }))
  expect(inspectorDimensions.clientHeight).toBeLessThanOrEqual(800)
  expect(inspectorDimensions.scrollHeight).toBeGreaterThan(inspectorDimensions.clientHeight)
  expect(inspectorDimensions.overflowY).toMatch(/auto|scroll/)
  await page.getByTitle('Advance one hour').click()
  await expect(page.getByText('Person inspector')).toBeVisible()
  await expect(page.getByText('Person hooked')).toBeVisible()
})

test('the same seed and step count produce the same digest', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByText('Seeded Valley')).toBeVisible()
  await page.getByTitle('Advance one hour').click()
  await expect(page.getByText('Day 0 · 01:00')).toBeVisible()
  const firstDigest = await page.locator('.fact').filter({ hasText: 'STATE' }).locator('strong').textContent()
  expect(firstDigest).toBe('456aceb484')
  await page.getByRole('button', { name: 'Reset' }).click()
  await expect(page.getByText('Day 0 · 00:00')).toBeVisible()
  await page.getByTitle('Advance one hour').click()
  await expect(page.getByText('Day 0 · 01:00')).toBeVisible()
  await expect(page.locator('.fact').filter({ hasText: 'STATE' }).locator('strong')).toHaveText(firstDigest ?? '')
})

test('encounter events navigate between hooked people and their relationships', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByText('Seeded Valley')).toBeVisible()
  for (let hour = 0; hour < 24; hour += 1) await page.getByTitle('Advance one hour').click()
  await expect(page.getByText('Day 1 · 00:00')).toBeVisible()
  const encounter = page.locator('.event-row').filter({ hasText: 'PERSON ENCOUNTERED' }).first()
  await expect(encounter).toBeVisible()
  await expect(encounter.getByRole('button')).toHaveCount(2)
  await encounter.getByRole('button').first().click()
  await expect(page.getByText('Last encounter')).toBeVisible()
  await expect(page.getByText(/outcome probability/)).toBeVisible()
  await expect(page.locator('.relationship-list button').first()).toBeVisible()
  const relationshipTarget = await page.locator('.relationship-list button').first().getAttribute('aria-label')
  await page.locator('.relationship-list button').first().click()
  await expect(page.locator('.right-panel .panel-title').first().locator('span')).toHaveText((relationshipTarget ?? '').replace('Hook ', ''))
})
