import { expect, test } from '@playwright/test'

test('creates, steps, inspects, and saves a deterministic world', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByText('Seeded Valley')).toBeVisible()
  await expect(page.getByText('Day 0 · 00:00')).toBeVisible()
  await page.getByTitle('Advance one hour').click()
  await expect(page.getByText('Day 0 · 01:00')).toBeVisible()
  await page.getByPlaceholder('Snapshot name').fill('First hour')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByText('First hour')).toBeVisible()
  await expect(page.getByText('CLOCK ADVANCED')).toBeVisible()
  await page.getByRole('button', { name: /Inspect person-/ }).first().click()
  await expect(page.getByText('Person inspector')).toBeVisible()
  await expect(page.getByText('Tracking live')).toBeVisible()
  await expect(page.getByText('Last decision')).toBeVisible()
  await expect(page.getByText(/selection probability/)).toBeVisible()
  await page.getByTitle('Advance one hour').click()
  await expect(page.getByText('Person inspector')).toBeVisible()
  await expect(page.getByText('Tracking live')).toBeVisible()
})

test('the same seed and step count produce the same digest', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByText('Seeded Valley')).toBeVisible()
  await page.getByTitle('Advance one hour').click()
  await expect(page.getByText('Day 0 · 01:00')).toBeVisible()
  const firstDigest = await page.locator('.fact').filter({ hasText: 'STATE' }).locator('strong').textContent()
  expect(firstDigest).toBe('947810a836')
  await page.getByRole('button', { name: 'Reset' }).click()
  await expect(page.getByText('Day 0 · 00:00')).toBeVisible()
  await page.getByTitle('Advance one hour').click()
  await expect(page.getByText('Day 0 · 01:00')).toBeVisible()
  await expect(page.locator('.fact').filter({ hasText: 'STATE' }).locator('strong')).toHaveText(firstDigest ?? '')
})
